### ISSUE TITLE
Проверка задания

### ISSUE THREAD

**Issue by avito-ds** [Mixaer23/avito-case#1]
Привет!
К сожалению решение упало с ошибкой, проверить решение локально можно запустив команду
`docker-compose -f docker-compose.yaml up`
Ошибка:
```
Traceback (most recent call last):
  File "lib/run.py", line 163, in <module>
    test.run()
  File "lib/run.py", line 126, in run
    task1_prediction, task2_prediction = self.process()
  File "lib/run.py", line 145, in process
    task1_prediction = start(test)
  File "/app/lib/my_model.py", line 57, in start
    df.columns = ['index', 'prediction']
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 5475, in __setattr__
    return object.__setattr__(self, name, value)
  File "pandas/_libs/properties.pyx", line 66, in pandas._libs.properties.AxisProperty.__set__
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 669, in _set_axis
    self._mgr.set_axis(axis, labels)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/managers.py", line 220, in set_axis
    raise ValueError(
ValueError: Length mismatch: Expected axis has 1 elements, new values have 2 elements
```

**Comment by avito-ds** [comment]
Пока что закроем issue, если будут какие-то обновления, то можно переоткрыть этот или создать новый.
